from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
import json
import os
from typing import Dict, List, Any, Optional

router = APIRouter()

class TreeNodeResponse(BaseModel):
    id: str
    path_abs: str
    parent_id: Optional[str]
    name: str
    is_dir: int
    ext: str
    size_bytes: Optional[int]
    when_created: Optional[float]
    when_modified: Optional[float]
    is_synthetic: bool

class TreeDataResponse(BaseModel):
    nodes: Dict[str, TreeNodeResponse]
    adjacency_list: Dict[str, List[str]]
    root_ids: List[str]
    metadata: Dict[str, int]

# Path to the tree data file (generated by tree.py)
TREE_DATA_PATH = os.path.join(os.path.dirname(__file__), "../../../data/file_tree.json")

@router.get("/tree", response_model=TreeDataResponse)
async def get_tree_structure():
    """
    Get the complete file tree structure from the generated tree data.
    This endpoint serves the tree structure created by the tree.py script.
    """
    try:
        # Check if tree data file exists
        if not os.path.exists(TREE_DATA_PATH):
            raise HTTPException(
                status_code=404, 
                detail=f"Tree data not found. Please run the tree generation script first. Looking for: {TREE_DATA_PATH}"
            )
        
        # Load and return the tree data
        with open(TREE_DATA_PATH, 'r', encoding='utf-8') as f:
            tree_data = json.load(f)
        
        return tree_data
        
    except json.JSONDecodeError as e:
        raise HTTPException(
            status_code=500,
            detail=f"Invalid JSON in tree data file: {str(e)}"
        )
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Error loading tree data: {str(e)}"
        )

@router.get("/tree/stats")
async def get_tree_stats():
    """
    Get basic statistics about the tree structure.
    """
    try:
        if not os.path.exists(TREE_DATA_PATH):
            raise HTTPException(status_code=404, detail="Tree data not found")
        
        with open(TREE_DATA_PATH, 'r', encoding='utf-8') as f:
            tree_data = json.load(f)
        
        # Return just the metadata
        return {
            "metadata": tree_data.get("metadata", {}),
            "data_file_path": TREE_DATA_PATH,
            "file_exists": True,
            "last_modified": os.path.getmtime(TREE_DATA_PATH) if os.path.exists(TREE_DATA_PATH) else None
        }
        
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Error loading tree stats: {str(e)}"
        )

@router.post("/tree/refresh")
async def refresh_tree():
    """
    Trigger a refresh of the tree data by running the tree generation script.
    Note: This is a placeholder - you might want to implement actual script execution.
    """
    try:
        # For now, just check if the file exists and return its stats
        if os.path.exists(TREE_DATA_PATH):
            stat = os.stat(TREE_DATA_PATH)
            return {
                "message": "Tree data file found",
                "last_modified": stat.st_mtime,
                "size_bytes": stat.st_size,
                "path": TREE_DATA_PATH
            }
        else:
            raise HTTPException(
                status_code=404,
                detail="Tree data file not found. Please run tree.py script to generate it."
            )
            
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Error checking tree data: {str(e)}"
        )
